### ISSUE TITLE
Fix or hide spurious warnings

### ISSUE THREAD

**Issue by ejnnr** [ejnnr/cupbearer#20]
Running `pytest` gives quite a few deprecation and other warnings (and some of the scripts also give a a few). None of them are actually concerning, but would be nice to either fix or just suppress them where appropriate.

**Comment by VRehnberg** [comment]
Current status: https://github.com/ejnnr/cupbearer/pull/22 got rid of most of them and https://github.com/ejnnr/cupbearer/commit/b995b2dec6ee58957d83700d05214b72202809bc got rid of another one

I do currently see a few warnings in clean install:
```
<frozen importlib._bootstrap>:488
  <frozen importlib._bootstrap>:488: DeprecationWarning: Type google._upb._message.MessageMapContainer uses PyType_Spec with a metaclass that has custom tp_new. This is deprecated and will no longer be allowed in Python 3.14.

<frozen importlib._bootstrap>:488
  <frozen importlib._bootstrap>:488: DeprecationWarning: Type google._upb._message.ScalarMapContainer uses PyType_Spec with a metaclass that has custom tp_new. This is deprecated and will no longer be allowed in Python 3.14.

../../../../../miniconda3/envs/cupbearer/lib/python3.12/site-packages/jupyter_client/connect.py:22
  /home/vikren/miniconda3/envs/cupbearer/lib/python3.12/site-packages/jupyter_client/connect.py:22: DeprecationWarning: Jupyter is migrating its paths to use standard platformdirs
  given by the platformdirs library.  To remove this warning and
  see the appropriate new directories, set the environment variable
  `JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
  The use of platformdirs will be the default in `jupyter_core` v6
    from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write

tests/test_data.py: 14 warnings
  /home/vikren/miniconda3/envs/cupbearer/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=11514) is multi-threaded, use of fork() may lead to deadlocks in the child.
    self.pid = os.fork()
```
 - one warning is from loading `transformer_lens` (think it has to do with an old version requirement on protobuf from wandb)
 - other is from loading `loguru`
 - third one is from using 2 workers in the dataloading, not sure what the other forks come from
 
 None of these are really connected to cupbearer itself in particular.

**Comment by ejnnr** [comment]
Thanks, I'll close this then, agree the remaining ones seem out of scope and it's not worth filtering out all warnings from other packages (especially because they'll depend a lot on the exact environment)
